name: dogma_connection
version: 0.0.1
description: Data connection for Dart.
environment:
  sdk: '>=1.12.0 <2.0.0'
dev_dependencies:
  test: ^0.12.4+6
author: Don Olmstead <don.j.olmstead@gmail.com>
homepage: http://dogma-dart.github.io/
